# Lab 8: Implementation and Performance Evaluation of Categorical Naive Bayes Classifier

## Data Preprocessing:
## Load the dataset and separate the input features (Outlook, Temperature, Humidity, Wind) from the target variable (Play).
## Convert all categorical feature values and target labels into numerical representations using an appropriate encoding technique.


### Import Required Libraries

In this step, we import all the necessary Python libraries required for data preprocessing, model training, evaluation, and comparison.

In [ ]:
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import CategoricalNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import warnings
warnings.filterwarnings("ignore")


from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

## Load the Play Tennis Dataset

Load the Play Tennis dataset into a Pandas DataFrame and display the dataset for verification.

In [ ]:
data = pd.read_csv("play_tennis.csv")

print("Original Dataset:")
data

Original Dataset:

    No   Outlook Temperature Humidity    Wind Play Tennis
0    1     Sunny         Hot     High    Weak          No
1    2     Sunny         Hot     High  Strong          No
2    3  Overcast         Hot     High    Weak         Yes
3    4      Rain        Mild     High    Weak         Yes
4    5      Rain        Cool   Normal    Weak         Yes
5    6      Rain        Cool   Normal  Strong          No
6    7  Overcast        Cool   Normal  Strong         Yes
7    8     Sunny        Mild     High    Weak          No
8    9     Sunny        Cool   Normal    Weak         Yes
9   10      Rain        Mild   Normal    Weak         Yes
10  11     Sunny        Mild   Normal  Strong         Yes
11  12  Overcast        Mild     High  Strong         Yes
12  13  Overcast         Hot   Normal    Weak         Yes
13  14      Rain        Mild     High  Strong          No
14  15     Sunny        Cool     High    Weak          No
15  16     Sunny        Cool     High  Strong          No
16  17     Sunny         Hot   Normal    Weak         Yes
17  18     Sunny         Hot   Normal  Strong         Yes
18  19  Overcast        Cool     High    Weak         Yes
19  20  Overcast        Cool     High  Strong         Yes
20  21  Overcast        Mild   Normal    Weak         Yes
21  22  Overcast        Mild   Normal  Strong         Yes
22  23      Rain         Hot     High    Weak         Yes
23  24      Rain         Hot     High  Strong          No
24  25      Rain         Hot   Normal    Weak         Yes
25  26      Rain         Hot   Normal  Strong          No
26  27      Rain        Cool     High    Weak         Yes
27  28      Rain        Cool     High  Strong          No
28  29      Rain        Mild   Normal  Strong         Yes
29  30     Sunny        Mild     High  Strong          No
30  31     Sunny        Cool   Normal  Strong         Yes
31  32     Sunny         Hot     High    Weak          No
32  33     Sunny         Hot   Normal    Weak         Yes
33  34     Sunny        Mild   Normal    Weak         Yes
34  35  Overcast         Hot     High  Strong         Yes
35  36  Overcast         Hot   Normal  Strong         Yes
36  37  Overcast        Cool   Normal    Weak         Yes
37  38  Overcast        Mild     High    Weak         Yes
38  39      Rain        Mild     High    Weak         Yes
39  40      Rain        Cool   Normal    Weak         Yes
40  41      Rain         Hot     High  Strong          No
41  42     Sunny        Cool     High    Weak          No
42  43     Sunny        Mild   Normal  Strong         Yes
43  44     Sunny         Hot     High  Strong          No
44  45  Overcast        Cool     High    Weak         Yes
45  46  Overcast        Mild   Normal  Strong         Yes
46  47      Rain        Mild   Normal    Weak         Yes
47  48      Rain        Cool     High  Strong          No
48  49     Sunny        Cool   Normal    Weak         Yes
49  50  Overcast         Hot   Normal    Weak         Yes

## Separate Input Features and Target Variable

Separate the predictor variables (Outlook, Temperature, Humidity, Wind) from the target variable (Play).

In [ ]:
X = data[['Outlook', 'Temperature', 'Humidity', 'Wind']]
y = data['Play Tennis']

print("Features:")
display(X)

print("Target:")
display(y)

Features:

     Outlook Temperature Humidity    Wind
0      Sunny         Hot     High    Weak
1      Sunny         Hot     High  Strong
2   Overcast         Hot     High    Weak
3       Rain        Mild     High    Weak
4       Rain        Cool   Normal    Weak
5       Rain        Cool   Normal  Strong
6   Overcast        Cool   Normal  Strong
7      Sunny        Mild     High    Weak
8      Sunny        Cool   Normal    Weak
9       Rain        Mild   Normal    Weak
10     Sunny        Mild   Normal  Strong
11  Overcast        Mild     High  Strong
12  Overcast         Hot   Normal    Weak
13      Rain        Mild     High  Strong
14     Sunny        Cool     High    Weak
15     Sunny        Cool     High  Strong
16     Sunny         Hot   Normal    Weak
17     Sunny         Hot   Normal  Strong
18  Overcast        Cool     High    Weak
19  Overcast        Cool     High  Strong
20  Overcast        Mild   Normal    Weak
21  Overcast        Mild   Normal  Strong
22      Rain         Hot     High    Weak
23      Rain         Hot     High  Strong
24      Rain         Hot   Normal    Weak
25      Rain         Hot   Normal  Strong
26      Rain        Cool     High    Weak
27      Rain        Cool     High  Strong
28      Rain        Mild   Normal  Strong
29     Sunny        Mild     High  Strong
30     Sunny        Cool   Normal  Strong
31     Sunny         Hot     High    Weak
32     Sunny         Hot   Normal    Weak
33     Sunny        Mild   Normal    Weak
34  Overcast         Hot     High  Strong
35  Overcast         Hot   Normal  Strong
36  Overcast        Cool   Normal    Weak
37  Overcast        Mild     High    Weak
38      Rain        Mild     High    Weak
39      Rain        Cool   Normal    Weak
40      Rain         Hot     High  Strong
41     Sunny        Cool     High    Weak
42     Sunny        Mild   Normal  Strong
43     Sunny         Hot     High  Strong
44  Overcast        Cool     High    Weak
45  Overcast        Mild   Normal  Strong
46      Rain        Mild   Normal    Weak
47      Rain        Cool     High  Strong
48     Sunny        Cool   Normal    Weak
49  Overcast         Hot   Normal    Weak

Target:

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
14     No
15     No
16    Yes
17    Yes
18    Yes
19    Yes
20    Yes
21    Yes
22    Yes
23     No
24    Yes
25     No
26    Yes
27     No
28    Yes
29     No
30    Yes
31     No
32    Yes
33    Yes
34    Yes
35    Yes
36    Yes
37    Yes
38    Yes
39    Yes
40     No
41     No
42    Yes
43     No
44    Yes
45    Yes
46    Yes
47     No
48    Yes
49    Yes
Name: Play Tennis, dtype: object

## Data Preprocessing – Encode Categorical Values

Convert all categorical feature values and target labels into numerical values using Label Encoding so that they can be processed by machine learning algorithms.

In [ ]:
feature_encoders = {}

for column in X.columns:
    encoder = LabelEncoder()
    X[column] = encoder.fit_transform(X[column])
    feature_encoders[column] = encoder

target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)

print("Encoded Features:")
display(X)

print("Encoded Target:")
print(y)

Encoded Features:

    Outlook  Temperature  Humidity  Wind
0         2            1         0     1
1         2            1         0     0
2         0            1         0     1
3         1            2         0     1
4         1            0         1     1
5         1            0         1     0
6         0            0         1     0
7         2            2         0     1
8         2            0         1     1
9         1            2         1     1
10        2            2         1     0
11        0            2         0     0
12        0            1         1     1
13        1            2         0     0
14        2            0         0     1
15        2            0         0     0
16        2            1         1     1
17        2            1         1     0
18        0            0         0     1
19        0            0         0     0
20        0            2         1     1
21        0            2         1     0
22        1            1         0     1
23        1            1         0     0
24        1            1         1     1
25        1            1         1     0
26        1            0         0     1
27        1            0         0     0
28        1            2         1     0
29        2            2         0     0
30        2            0         1     0
31        2            1         0     1
32        2            1         1     1
33        2            2         1     1
34        0            1         0     0
35        0            1         1     0
36        0            0         1     1
37        0            2         0     1
38        1            2         0     1
39        1            0         1     1
40        1            1         0     0
41        2            0         0     1
42        2            2         1     0
43        2            1         0     0
44        0            0         0     1
45        0            2         1     0
46        1            2         1     1
47        1            0         0     0
48        2            0         1     1
49        0            1         1     1

Encoded Target:
[0 0 1 1 1 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1
 1 1 1 0 0 1 0 1 1 1 0 1 1]

## Dataset Partitioning

Split the encoded dataset into training and testing subsets using an 80:20 train-test ratio.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training Samples :", len(X_train))
print("Testing Samples  :", len(X_test))

Training Samples : 40
Testing Samples  : 10

## Train the Categorical Naive Bayes Classifier

Create and train a Categorical Naive Bayes (CategoricalNB) classifier using the training dataset.

In [ ]:
nb_model = CategoricalNB()

nb_model.fit(X_train, y_train)

print("Categorical Naive Bayes Model Trained Successfully.")

Categorical Naive Bayes Model Trained Successfully.

## Predict the Test Dataset

Use the trained Categorical Naive Bayes model to predict the class labels for the testing dataset.

In [ ]:
y_pred = nb_model.predict(X_test)

print("Predicted Labels:")
print(y_pred)

Predicted Labels:
[0 1 1 1 1 1 0 1 1 1]

## Evaluate the Naive Bayes Model

Evaluate the performance of the trained model by calculating:

- Model Accuracy
- Confusion Matrix
- Classification Report (Precision, Recall, F1-Score)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:")
print(accuracy)

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

Accuracy:
0.8

Confusion Matrix
[[1 1]
 [1 7]]

Classification Report
              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.88      0.88      0.88         8

    accuracy                           0.80        10
   macro avg       0.69      0.69      0.69        10
weighted avg       0.80      0.80      0.80        10

## Single-Sample Prediction

Predict whether a person will play tennis for the following weather conditions:

- Outlook: Sunny
- Temperature: Cool
- Humidity: High
- Wind: Strong

Display both the predicted class label and the corresponding class probabilities.

In [ ]:
sample = {
    "Outlook": "Sunny",
    "Temperature": "Cool",
    "Humidity": "High",
    "Wind": "Strong"
}

sample_encoded = [[
    feature_encoders["Outlook"].transform([sample["Outlook"]])[0],
    feature_encoders["Temperature"].transform([sample["Temperature"]])[0],
    feature_encoders["Humidity"].transform([sample["Humidity"]])[0],
    feature_encoders["Wind"].transform([sample["Wind"]])[0]
]]

prediction = nb_model.predict(sample_encoded)
probability = nb_model.predict_proba(sample_encoded)

print("Input Weather:")
print(sample)

print("\nPrediction:")
print(target_encoder.inverse_transform(prediction)[0])

print("\nClass Probabilities:")

for label, prob in zip(target_encoder.classes_, probability[0]):
    print(label, ":", round(prob,4))

Input Weather:
{'Outlook': 'Sunny', 'Temperature': 'Cool', 'Humidity': 'High', 'Wind': 'Strong'}

Prediction:
No

Class Probabilities:
No : 0.9256
Yes : 0.0744

## Train the Decision Tree Classifier

Train a Decision Tree classifier using the same training dataset and evaluate its prediction performance.

In [ ]:
dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

dt_prediction = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_prediction)

dt_sample_prediction = dt_model.predict(sample_encoded)

dt_probability = dt_model.predict_proba(sample_encoded)

print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.8

## Train the Logistic Regression Classifier

Train a Logistic Regression classifier using the same training dataset and evaluate its prediction performance.

In [ ]:
lr_model = LogisticRegression(max_iter=500)

lr_model.fit(X_train, y_train)

lr_prediction = lr_model.predict(X_test)

lr_accuracy = accuracy_score(y_test, lr_prediction)

lr_sample_prediction = lr_model.predict(sample_encoded)

lr_probability = lr_model.predict_proba(sample_encoded)

print("Logistic Regression Accuracy:", lr_accuracy)

Logistic Regression Accuracy: 0.4

## Train the Support Vector Machine (SVM)

Train a Support Vector Machine classifier using the same training dataset and evaluate its prediction performance.

In [ ]:
svm_model = SVC(probability=True)

svm_model.fit(X_train, y_train)

svm_prediction = svm_model.predict(X_test)

svm_accuracy = accuracy_score(y_test, svm_prediction)

svm_sample_prediction = svm_model.predict(sample_encoded)

svm_probability = svm_model.predict_proba(sample_encoded)

print("SVM Accuracy:", svm_accuracy)

SVM Accuracy: 0.7

## Compare All Models

Compare the performance of the following classifiers:

- Categorical Naive Bayes
- Decision Tree
- Logistic Regression
- Support Vector Machine (SVM)

Comparison is based on:

- Test Accuracy
- Single-Sample Prediction

In [ ]:
comparison = pd.DataFrame({
    "Model": [
        "Categorical Naive Bayes",
        "Decision Tree",
        "Logistic Regression",
        "Support Vector Machine"
    ],
    "Accuracy": [
        accuracy,
        dt_accuracy,
        lr_accuracy,
        svm_accuracy
    ],
    "Prediction": [
        target_encoder.inverse_transform(prediction)[0],
        target_encoder.inverse_transform(dt_sample_prediction)[0],
        target_encoder.inverse_transform(lr_sample_prediction)[0],
        target_encoder.inverse_transform(svm_sample_prediction)[0]
    ]
})

comparison

                     Model  Accuracy Prediction
0  Categorical Naive Bayes       0.8         No
1            Decision Tree       0.8         No
2      Logistic Regression       0.4         No
3   Support Vector Machine       0.7         No

## Compare Class Probabilities

Compare the predicted class probabilities generated by all four machine learning models for the given weather conditions.

In [ ]:
print("Categorical Naive Bayes")
print(nb_model.predict_proba(sample_encoded))

print("\nDecision Tree")
print(dt_probability)

print("\nLogistic Regression")
print(lr_probability)

print("\nSupport Vector Machine")
print(svm_probability)

Categorical Naive Bayes
[[0.92560203 0.07439797]]

Decision Tree
[[1. 0.]]

Logistic Regression
[[0.94392742 0.05607258]]

Support Vector Machine
[[0.98090704 0.01909296]]

In [106]:
print("""
Analysis Report

1. Categorical Naive Bayes assumes all features are independent and computes probabilities using Bayes' theorem.
2. Decision Tree makes predictions by following learned decision rules, often giving probabilities of 0 or 1.
3. Logistic Regression predicts using a linear model with sigmoid probabilities, while SVM maximizes the margin between classes and estimates probabilities through calibration.
4. Due to their different learning methods, the models may produce different confidence scores and, in some cases, different predictions for the same weather conditions.
""")

Analysis Report

1. Categorical Naive Bayes assumes all features are independent and computes probabilities using Bayes' theorem.
2. Decision Tree makes predictions by following learned decision rules, often giving probabilities of 0 or 1.
3. Logistic Regression predicts using a linear model with sigmoid probabilities, while SVM maximizes the margin between classes and estimates probabilities through calibration.
4. Due to their different learning methods, the models may produce different confidence scores and, in some cases, different predictions for the same weather conditions.